static const char *RcsId = "$Header$";
//+=============================================================================
//
// file :         TangoAccessControlStateMachine.cpp
//
// description :  C++ source for the TangoAccessControl and its alowed. 
//                method for commands and attributes
//
// project :      TANGO Device Server
//
// $Author$
//
// $Revision$
//
// $Log$
//
// copyleft :     European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#include <tango.h>
#include <TangoAccessControl.h>
#include <TangoAccessControlClass.h>

/*====================================================================
 *	This file contains the methods to allow commands and attributes
 * read or write execution.
 *
 * If you wand to add your own code, add it between 
 * the "End/Re-Start of Generated Code" comments.
 *
 * If you want, you can also add your own methods.
 *====================================================================
 */

namespace TangoAccessControl_ns
{

//=================================================
//		Attributes Allowed Methods
//=================================================


//=================================================
//		Commands Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		TangoAccessControl::is_AddAddressForUser_allowed
// 
// description : 	Execution allowed for AddAddressForUser command.
//
//-----------------------------------------------------------------------------
bool TangoAccessControl::is_AddAddressForUser_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoAccessControl::is_AddDeviceForUser_allowed
// 
// description : 	Execution allowed for AddDeviceForUser command.
//
//-----------------------------------------------------------------------------
bool TangoAccessControl::is_AddDeviceForUser_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoAccessControl::is_CloneUser_allowed
// 
// description : 	Execution allowed for CloneUser command.
//
//-----------------------------------------------------------------------------
bool TangoAccessControl::is_CloneUser_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoAccessControl::is_GetAccess_allowed
// 
// description : 	Execution allowed for GetAccess command.
//
//-----------------------------------------------------------------------------
bool TangoAccessControl::is_GetAccess_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoAccessControl::is_GetAddressByUser_allowed
// 
// description : 	Execution allowed for GetAddressByUser command.
//
//-----------------------------------------------------------------------------
bool TangoAccessControl::is_GetAddressByUser_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoAccessControl::is_GetAllowedCommands_allowed
// 
// description : 	Execution allowed for GetAllowedCommands command.
//
//-----------------------------------------------------------------------------
bool TangoAccessControl::is_GetAllowedCommands_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoAccessControl::is_GetDeviceByUser_allowed
// 
// description : 	Execution allowed for GetDeviceByUser command.
//
//-----------------------------------------------------------------------------
bool TangoAccessControl::is_GetDeviceByUser_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoAccessControl::is_GetDeviceClass_allowed
// 
// description : 	Execution allowed for GetDeviceClass command.
//
//-----------------------------------------------------------------------------
bool TangoAccessControl::is_GetDeviceClass_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoAccessControl::is_GetUsers_allowed
// 
// description : 	Execution allowed for GetUsers command.
//
//-----------------------------------------------------------------------------
bool TangoAccessControl::is_GetUsers_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoAccessControl::is_RemoveAddressForUser_allowed
// 
// description : 	Execution allowed for RemoveAddressForUser command.
//
//-----------------------------------------------------------------------------
bool TangoAccessControl::is_RemoveAddressForUser_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoAccessControl::is_RemoveDeviceForUser_allowed
// 
// description : 	Execution allowed for RemoveDeviceForUser command.
//
//-----------------------------------------------------------------------------
bool TangoAccessControl::is_RemoveDeviceForUser_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoAccessControl::is_RemoveUser_allowed
// 
// description : 	Execution allowed for RemoveUser command.
//
//-----------------------------------------------------------------------------
bool TangoAccessControl::is_RemoveUser_allowed(const CORBA::Any &any)
{
	if (get_state() == Tango::FAULT)
	{
		//	End of Generated Code

		//	Re-Start of Generated Code
		return false;
	}
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoAccessControl::is_RegisterService_allowed
// 
// description : 	Execution allowed for RegisterService command.
//
//-----------------------------------------------------------------------------
bool TangoAccessControl::is_RegisterService_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoAccessControl::is_UnregisterService_allowed
// 
// description : 	Execution allowed for UnregisterService command.
//
//-----------------------------------------------------------------------------
bool TangoAccessControl::is_UnregisterService_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

}	// namespace TangoAccessControl_ns
