static const char *RcsId = "$Header$";
//+=============================================================================
//
// file :         TangoTestStateMachine.cpp
//
// description :  C++ source for the TangoTest and its alowed. 
//                method for commands and attributes
//
// project :      TANGO Device Server
//
// $Author$
//
// $Revision$
//
// $Log$
//
// copyleft :     European Synchrotron Radiation Facility
//                BP 220, Grenoble 38043
//                FRANCE
//
//-=============================================================================
//
//  		This file is generated by POGO
//	(Program Obviously used to Generate tango Object)
//
//         (c) - Software Engineering Group - ESRF
//=============================================================================

#include <tango.h>
#include <TangoTest.h>
#include <TangoTestClass.h>

/*====================================================================
 *	This file contains the methods to allow commands and attributes
 * read or write execution.
 *
 * If you wand to add your own code, add it between 
 * the "End/Re-Start of Generated Code" comments.
 *
 * If you want, you can also add your own methods.
 *====================================================================
 */

namespace TangoTest
{

//=================================================
//		Attributes Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_short_scalar_ro_allowed
// 
// description : 	Read/Write allowed for short_scalar_ro attribute.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_short_scalar_ro_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_short_scalar_allowed
// 
// description : 	Read/Write allowed for short_scalar attribute.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_short_scalar_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_long_scalar_allowed
// 
// description : 	Read/Write allowed for long_scalar attribute.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_long_scalar_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_double_scalar_allowed
// 
// description : 	Read/Write allowed for double_scalar attribute.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_double_scalar_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_string_scalar_allowed
// 
// description : 	Read/Write allowed for string_scalar attribute.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_string_scalar_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_short_spectrum_allowed
// 
// description : 	Read/Write allowed for short_spectrum attribute.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_short_spectrum_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_long_spectrum_allowed
// 
// description : 	Read/Write allowed for long_spectrum attribute.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_long_spectrum_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_double_spectrum_allowed
// 
// description : 	Read/Write allowed for double_spectrum attribute.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_double_spectrum_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_short_image_allowed
// 
// description : 	Read/Write allowed for short_image attribute.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_short_image_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_long_image_allowed
// 
// description : 	Read/Write allowed for long_image attribute.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_long_image_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_double_image_allowed
// 
// description : 	Read/Write allowed for double_image attribute.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_double_image_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_short_scalar_w_allowed
// 
// description : 	Read/Write allowed for short_scalar_w attribute.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_short_scalar_w_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_short_scalar_rww_allowed
// 
// description : 	Read/Write allowed for short_scalar_rww attribute.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_short_scalar_rww_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_long_scalar_w_allowed
// 
// description : 	Read/Write allowed for long_scalar_w attribute.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_long_scalar_w_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_long_scalar_rww_allowed
// 
// description : 	Read/Write allowed for long_scalar_rww attribute.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_long_scalar_rww_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_double_scalar_w_allowed
// 
// description : 	Read/Write allowed for double_scalar_w attribute.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_double_scalar_w_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_double_scalar_rww_allowed
// 
// description : 	Read/Write allowed for double_scalar_rww attribute.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_double_scalar_rww_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_ampli_allowed
// 
// description : 	Read/Write allowed for ampli attribute.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_ampli_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_wave_allowed
// 
// description : 	Read/Write allowed for wave attribute.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_wave_allowed(Tango::AttReqType type)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

//=================================================
//		Commands Allowed Methods
//=================================================

//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_DevVoid_allowed
// 
// description : 	Execution allowed for DevVoid command.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_DevVoid_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_DevBoolean_allowed
// 
// description : 	Execution allowed for DevBoolean command.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_DevBoolean_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_DevShort_allowed
// 
// description : 	Execution allowed for DevShort command.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_DevShort_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_DevUShort_allowed
// 
// description : 	Execution allowed for DevUShort command.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_DevUShort_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_DevLong_allowed
// 
// description : 	Execution allowed for DevLong command.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_DevLong_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_DevULong_allowed
// 
// description : 	Execution allowed for DevULong command.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_DevULong_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_DevFloat_allowed
// 
// description : 	Execution allowed for DevFloat command.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_DevFloat_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_DevDouble_allowed
// 
// description : 	Execution allowed for DevDouble command.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_DevDouble_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_DevString_allowed
// 
// description : 	Execution allowed for DevString command.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_DevString_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_DevVarCharArray_allowed
// 
// description : 	Execution allowed for DevVarCharArray command.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_DevVarCharArray_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_DevVarShortArray_allowed
// 
// description : 	Execution allowed for DevVarShortArray command.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_DevVarShortArray_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_DevVarUShortArray_allowed
// 
// description : 	Execution allowed for DevVarUShortArray command.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_DevVarUShortArray_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_DevVarLongArray_allowed
// 
// description : 	Execution allowed for DevVarLongArray command.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_DevVarLongArray_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_DevVarULongArray_allowed
// 
// description : 	Execution allowed for DevVarULongArray command.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_DevVarULongArray_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_DevVarFloatArray_allowed
// 
// description : 	Execution allowed for DevVarFloatArray command.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_DevVarFloatArray_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_DevVarDoubleArray_allowed
// 
// description : 	Execution allowed for DevVarDoubleArray command.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_DevVarDoubleArray_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_DevVarStringArray_allowed
// 
// description : 	Execution allowed for DevVarStringArray command.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_DevVarStringArray_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_DevVarLongStringArray_allowed
// 
// description : 	Execution allowed for DevVarLongStringArray command.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_DevVarLongStringArray_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}
//+----------------------------------------------------------------------------
//
// method : 		TangoTest::is_DevVarDoubleStringArray_allowed
// 
// description : 	Execution allowed for DevVarDoubleStringArray command.
//
//-----------------------------------------------------------------------------
bool TangoTest::is_DevVarDoubleStringArray_allowed(const CORBA::Any &any)
{
		//	End of Generated Code

		//	Re-Start of Generated Code
	return true;
}

}	// namespace TangoTest
