foldersTree = gFld("<b>Starter for Tango Administration</b>", "", "")
     insDoc(foldersTree, gLnk("Main Page", "", "main.html"))
aux1 = insFld(foldersTree, gFld("File List", "", "files.html"))
       insDoc(aux1, gLnk("ClassFactory.cpp", "", "ClassFactory_8cpp.html"))
       insDoc(aux1, gLnk("main.cpp", "", "main_8cpp.html"))
       insDoc(aux1, gLnk("Starter.cpp", "", "Starter_8cpp.html"))
       insDoc(aux1, gLnk("Starter.h", "", "Starter_8h.html"))
       insDoc(aux1, gLnk("StarterClass.cpp", "", "StarterClass_8cpp.html"))
       insDoc(aux1, gLnk("StarterClass.h", "", "StarterClass_8h.html"))
       insDoc(aux1, gLnk("StarterService.cpp", "", "StarterService_8cpp.html"))
       insDoc(aux1, gLnk("StarterService.h", "", "StarterService_8h.html"))
       insDoc(aux1, gLnk("StarterUtil.cpp", "", "StarterUtil_8cpp.html"))
       insDoc(aux1, gLnk("StarterUtil.h", "", "StarterUtil_8h.html"))
aux1 = insFld(foldersTree, gFld("Compound List", "", "annotated.html"))
       insDoc(aux1, gLnk("Starter::DevGetRunningServersCmd", "", "classStarter_1_1DevGetRunningServersCmd.html"))
       insDoc(aux1, gLnk("Starter::DevGetStopServersCmd", "", "classStarter_1_1DevGetStopServersCmd.html"))
       insDoc(aux1, gLnk("Starter::DevReadLogCmd", "", "classStarter_1_1DevReadLogCmd.html"))
       insDoc(aux1, gLnk("Starter::DevStartAllCmd", "", "classStarter_1_1DevStartAllCmd.html"))
       insDoc(aux1, gLnk("Starter::DevStartCmd", "", "classStarter_1_1DevStartCmd.html"))
       insDoc(aux1, gLnk("Starter::DevStopAllCmd", "", "classStarter_1_1DevStopAllCmd.html"))
       insDoc(aux1, gLnk("Starter::DevStopCmd", "", "classStarter_1_1DevStopCmd.html"))
       insDoc(aux1, gLnk("Starter::PollingState", "", "classStarter_1_1PollingState.html"))
       insDoc(aux1, gLnk("Starter::ServerControled", "", "structStarter_1_1ServerControled.html"))
       insDoc(aux1, gLnk("Starter::SharedData", "", "classStarter_1_1SharedData.html"))
       insDoc(aux1, gLnk("Starter::Starter", "", "classStarter_1_1Starter.html"))
       insDoc(aux1, gLnk("Starter::StarterClass", "", "classStarter_1_1StarterClass.html"))
       insDoc(aux1, gLnk("StarterService", "", "classStarterService.html"))
       insDoc(aux1, gLnk("Starter::StarterUtil", "", "classStarter_1_1StarterUtil.html"))
       insDoc(aux1, gLnk("Starter::StartPollingThreadCmd", "", "classStarter_1_1StartPollingThreadCmd.html"))
       insDoc(aux1, gLnk("Starter::UpdateServersInfoCmd", "", "classStarter_1_1UpdateServersInfoCmd.html"))
     insDoc(foldersTree, gLnk("Compound Members", "", "functions.html"))
aux1 = insFld(foldersTree, gFld("Namespace List", "", "namespaces.html"))
       insDoc(aux1, gLnk("Starter", "", "namespaceStarter.html"))
       insDoc(aux1, gLnk("std", "", "namespacestd.html"))
     insDoc(foldersTree, gLnk("File Members", "", "globals.html"))
     insDoc(foldersTree, gLnk("Namespace Members", "", "namespacemembers.html"))
