foldersTree = gFld("<b>TANGO Device Server for testing generic clients</b>", "", "")
     insDoc(foldersTree, gLnk("Main Page", "", "main.html"))
aux1 = insFld(foldersTree, gFld("File List", "", "files.html"))
       insDoc(aux1, gLnk("ClassFactory.cpp", "", "ClassFactory_8cpp.html"))
       insDoc(aux1, gLnk("main.cpp", "", "main_8cpp.html"))
       insDoc(aux1, gLnk("TangoTest.cpp", "", "TangoTest_8cpp.html"))
       insDoc(aux1, gLnk("TangoTest.h", "", "TangoTest_8h.html"))
       insDoc(aux1, gLnk("TangoTestClass.cpp", "", "TangoTestClass_8cpp.html"))
       insDoc(aux1, gLnk("TangoTestClass.h", "", "TangoTestClass_8h.html"))
aux1 = insFld(foldersTree, gFld("Compound List", "", "annotated.html"))
       insDoc(aux1, gLnk("TangoTest::DataGenerator", "", "classTangoTest_1_1DataGenerator.html"))
       insDoc(aux1, gLnk("TangoTest::DevBooleanCmd", "", "classTangoTest_1_1DevBooleanCmd.html"))
       insDoc(aux1, gLnk("TangoTest::DevDoubleCmd", "", "classTangoTest_1_1DevDoubleCmd.html"))
       insDoc(aux1, gLnk("TangoTest::DevFloatCmd", "", "classTangoTest_1_1DevFloatCmd.html"))
       insDoc(aux1, gLnk("TangoTest::DevLongCmd", "", "classTangoTest_1_1DevLongCmd.html"))
       insDoc(aux1, gLnk("TangoTest::DevShortCmd", "", "classTangoTest_1_1DevShortCmd.html"))
       insDoc(aux1, gLnk("TangoTest::DevStringCmd", "", "classTangoTest_1_1DevStringCmd.html"))
       insDoc(aux1, gLnk("TangoTest::DevULongCmd", "", "classTangoTest_1_1DevULongCmd.html"))
       insDoc(aux1, gLnk("TangoTest::DevUShortCmd", "", "classTangoTest_1_1DevUShortCmd.html"))
       insDoc(aux1, gLnk("TangoTest::DevVarCharArrayCmd", "", "classTangoTest_1_1DevVarCharArrayCmd.html"))
       insDoc(aux1, gLnk("TangoTest::DevVarDoubleArrayCmd", "", "classTangoTest_1_1DevVarDoubleArrayCmd.html"))
       insDoc(aux1, gLnk("TangoTest::DevVarDoubleStringArrayCmd", "", "classTangoTest_1_1DevVarDoubleStringArrayCmd.html"))
       insDoc(aux1, gLnk("TangoTest::DevVarFloatArrayCmd", "", "classTangoTest_1_1DevVarFloatArrayCmd.html"))
       insDoc(aux1, gLnk("TangoTest::DevVarLongArrayCmd", "", "classTangoTest_1_1DevVarLongArrayCmd.html"))
       insDoc(aux1, gLnk("TangoTest::DevVarLongStringArrayCmd", "", "classTangoTest_1_1DevVarLongStringArrayCmd.html"))
       insDoc(aux1, gLnk("TangoTest::DevVarShortArrayCmd", "", "classTangoTest_1_1DevVarShortArrayCmd.html"))
       insDoc(aux1, gLnk("TangoTest::DevVarStringArrayCmd", "", "classTangoTest_1_1DevVarStringArrayCmd.html"))
       insDoc(aux1, gLnk("TangoTest::DevVarULongArrayCmd", "", "classTangoTest_1_1DevVarULongArrayCmd.html"))
       insDoc(aux1, gLnk("TangoTest::DevVarUShortArrayCmd", "", "classTangoTest_1_1DevVarUShortArrayCmd.html"))
       insDoc(aux1, gLnk("TangoTest::DevVoidCmd", "", "classTangoTest_1_1DevVoidCmd.html"))
       insDoc(aux1, gLnk("TangoTest::TangoTest", "", "classTangoTest_1_1TangoTest.html"))
       insDoc(aux1, gLnk("TangoTest::TangoTestClass", "", "classTangoTest_1_1TangoTestClass.html"))
     insDoc(foldersTree, gLnk("Compound Members", "", "functions.html"))
aux1 = insFld(foldersTree, gFld("Namespace List", "", "namespaces.html"))
       insDoc(aux1, gLnk("TangoTest", "", "namespaceTangoTest.html"))
     insDoc(foldersTree, gLnk("File Members", "", "globals.html"))
     insDoc(foldersTree, gLnk("Namespace Members", "", "namespacemembers.html"))
